### ISSUE TITLE
coefficient

### ISSUE THREAD

**Issue by AwJHub** [malkemit/namizun#1]
3) Coefficient: By entering the number 3, you can enter the limit announced by the provider.
For example, if your ratio should be 10 uploads to 1 download, set the number to 1
 
But the acceptable entery is 3 to 12 how should put it 1 to 10?
![Annotation 2022-11-21 144934](https://user-images.githubusercontent.com/76947375/203038253-f0d743ee-8f08-466f-b9b4-9110d4024852.png)

**Comment by malkemit** [comment]
Oh, I forgot 0, I will fix it
