### ISSUE TITLE
ارور در خط source /var/www/namizun/venv/bin/activate && cd /var/www/namizun && pip install . && deactivate

### ISSUE THREAD

**Issue by rezabk** [malkemit/namizun#10]
source /var/www/namizun/venv/bin/activate && cd /var/www/namizun && pip install . && deactivate

ERROR : 

 Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-core==1.2.3) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
No matching distribution found for prettytable~=3.5.0 (from namizun-core==1.2.3)

![Capture](https://user-images.githubusercontent.com/77145261/206896834-14c8e0c4-d86e-4c57-a525-a250844e1031.PNG)

**Comment by malkemit** [comment]
use it on ubuntu 20 (python 3.8)
