### ISSUE TITLE
Could not find a version that satisfies

### ISSUE THREAD

**Issue by alijoon3376** [malkemit/namizun#11]
با درود فراوان 
بنده هنگام نصب setup.py  ارور زیر رو دریافت میکنم 

  Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-core==1.3.2) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
No matching distribution found for prettytable~=3.5.0 (from namizun-core==1.3.2)

**Comment by malkemit** [comment]
با سلام
رو اوبنتو ۲۰ (پایتون ۳.۸) تست کنید
