### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by pilot-code** [malkemit/namizun#12]
سلام 
ایا این اسکریپت از پورت خاصی برای دانلود  استفاده میکنه ؟ و اگه جواب بله هست چه پورتی و آیا قابل تغییر هست 
سوال دوم اینکه نحوه عمکرد این اسکریپت چگونه است و چطور مصرف سرور مارو تغییر میده 
متشکرم

**Comment by malkemit** [comment]
با سلام
فعلا اسکریپت از پورت های 3478, 28960, 27014, 27020, 25565, 27015, 3724, 5000 استفاده میکنه که عموما پورت های بازی های معروف هستند
و حتما این پورت ها رو ازاد بزارید

در مورد سوال دومتون هم این اسکریپت ترافیک udp به صورت فیک ارسال میکنه و اساسا سعی میکنه سرور شما رو مثل یک گیم سرور نشون بده

**Comment by alijoon3376** [comment]
> با سلام فعلا اسکریپت از پورت های 3478, 28960, 27014, 27020, 25565, 27015, 3724, 5000 استفاده میکنه که عموما پورت های بازی های معروف هستند و حتما این پورت ها رو ازاد بزارید
> 
> در مورد سوال دومتون هم این اسکریپت ترافیک udp به صورت فیک ارسال میکنه و اساسا سعی میکنه سرور شما رو مثل یک گیم سرور نشون بده

درود توسعه دهنده عزیز
آیا نیاز هست که همیشه اسکریپت در حال فعالیت باشد ؟ چون در سرور من بعد از چند ساعت فعالیت اسکریپت عملیات پورت فورواردینگ با اختلال مواجه شد و با استوپ کردن اسکریپت به حالت قبل برگشت. ممنون میشم در این خصوص توضیحی به بنده بدید

**Comment by malkemit** [comment]
با سلام
پورت های استفاده شده در این ابزار رو استفاده نکنید و همچنین پورت 6379 که برای دیتابیسش استفاده میشه و اینجوری به مشکل نمیخورین
حس میکنم بعضی از کانفیگ های شما از اون پورت ها استفاده  میکنن، کلا این پورت ها رو ازاد بزارین

در مورد فعالیت اسکریپت بهتره که همیشه فعال باشه تا همیشه با نسبت های درست اپلود داشته باشه
