### ISSUE TITLE
عدم قطع خودکار آپلود

### ISSUE THREAD

**Issue by admiraltidebringer** [malkemit/namizun#13]
سلام خسته نباشید
دوست عزیز من با قطع شدن خودکار آپلود سرویس مشکل دارم. می دونم که شما تلورانس قرار دارید، ولی چند بار که امتحان کردم، بعد از انتخاب ضریب 5 دیدم که آپلود بعد از 8 برابر شدن هم قطع نشده. خودم برا استفاده اول با  systemctl stop namizun.service سرویس رو قطع می کنم، بعد با namizun می رم تو پنل و تنظیمات رو انجام می دهم و بعد با systemctl daemon-reload و بعد systemctl start namizun.service سرویس رو اجرا می کنم. آیا مشکل قطع نشدن خودکار سرویس تو این مراحله؟

**Comment by malkemit** [comment]
با سلام
تو ورژن جدید کافیه تو پنل برین و گزینه ۱ بزنین و غیر فعال کنین و در نهایت با زدن گزینه ۹ ریلود کنین تا اوکی بشه و نیاز نیست سرویس رو مستقیم کاری داشته باشین

در واقع با زدن عدد ۹ میاین کاری میکنین که دوباره تنظیمات رو بخونه

روش خودتون هم تقریبا همین میشه و اگر دوست داشتین با خود پنل این کار رو بکنین

ضمنا دستور systemctl daemon-reload برای وقتیه که شما سرویسی رو ویرایش یا کم یا زیاد کردین و میخواین تو لیست جدیدش بره و نیاز نیست هی بزنین

**Comment by admiraltidebringer** [comment]
با تشکر
