### ISSUE TITLE
عمل نکردن روی ترافیک انلاین

### ISSUE THREAD

**Issue by bobyturk** [malkemit/namizun#14]
من تنظیمات رو مطابق اموزش انجام میدم ولی عملا ترافیک یک به یک ارسال میشه 

![photo_2022-12-13_12-43-54](https://user-images.githubusercontent.com/87282588/207276891-c1e68b7d-4831-4646-a615-37c32ed26e18.jpg)

**Comment by Argo160** [comment]
سلام وقت بخیر
این اسکریپت قراره محدودیت فعلی سرعت سرور تونل رو از بین ببره؟ یا مثل اون دستوری که در crontab ایجاد میکردیم عمل میکنه و گهگاهی دانلود یا آپلود انجام میده؟
متاسفانه توضیح جامعی در صفحه اصلی وجود نداره.

**Comment by malkemit** [comment]
با سلام تا وقتی که شما کمتر از یک گیگ مصرف داشته باشید اسکریپت کار نخواهد کرد

حداقل باید یک گیگ مصرف داشته باشید چون توی هر بار فعالیت اسکریپت، چندین گیگ اپلود خواهد شد

بهتر هست اسکریپ را بعد از ۵ الی ۱۰ گیگ مصرف فعال کنید


این اسکریپت فقط برای رفع محدودیت یک به ده هست و با توجه به رفتار آن در طول ۲۴ ساعت عملکرد تکراری نشان نخواهد داد و کمتر از سمت ارائه دهنده قابل پیگیری خواهد بود


در مورد سرعت تونل به رنج ای پی سرور خارجتون خیلی بستگی داره ، مثلا تونل به سرور های المان به خصوص هتزنر از سمت زیر ساخت محدود شده 

پیشنهاد میشه برای سرور خارج از کسی در خارج کمک بگیرید تا سروری از یک ارائه دهنده متفاوت تری تهیه کنید
به عنوان مثال سرعت تونل به سرور های والتر یا اپکلود بیشتر از هتزنر خواهد بود

**Comment by bobyturk** [comment]
ممنون از راهنماییتون . ولی این ارائه دهنده ها هم قیمتشون 4 برابر هتزنر هست و هم اینکه پهنای باند یک پنجم هتزنر میدن متاسفانه !
> 
> پیشنهاد میشه برای سرور خارج از کسی در خارج کمک بگیرید تا سروری از یک ارائه دهنده متفاوت تری تهیه کنید به عنوان مثال سرعت تونل به سرور های والتر یا اپکلود بیشتر از هتزنر خواهد بود

**Comment by malkemit** [comment]
به هر حال دیگه انتخاب شماست ولی چیزی که مشخصه بیشتر رنج های هتزنر محدودیت داره

میتونید از ovh هم استفاده بکنید اونم گزینه مناسبیه

کلا جا هایی که عموم مردم سراغش نمیرن، رنج های بهتری داره
