### ISSUE TITLE
Bypass the current bridges limits?

### ISSUE THREAD

**Issue by Argo160** [malkemit/namizun#15]
Hello everyone.
This is not an issue. just as a newbie trying to understand if we could use this script to bypass the current limitation on bridges in Iran or not?!
Thanks in advanced

**Comment by Argo160** [comment]
Anyway i did run the script.
Everything looks good regarding the ratio on namizun. 
but yet got the upload limit. which is nearly to zero on speed test :\

**Comment by malkemit** [comment]
hi

Download and upload traffic should not be symmetrical on Iranian servers. Therefore, with this script, you can solve this limitation, which is generally expressed as one to ten.

About your upload speed
The upload of this script is to the internal servers, which will all be lost.

And according to the coefficients you put in the script, it will not have much effect on your upload
