### ISSUE TITLE
قابلیت آپلود بدون توجه به نسبت

### ISSUE THREAD

**Issue by rainyboy7** [malkemit/namizun#16]
سلام. با تشکر از کار خوب شما . بنده یه سرور اختصاصی با ۱۴ ای پی دارم 
دو سه تا از آی پی ها رو گذاشتم مخصوص اپلود. اگه اسکریپت شما قابلیتی اضافه میشد که بدون توجه به نسبت یک به ده مداوم با درجه ۵ آپلود میکرد میشد روی اون سه ای پی بکار بردش. اینجوری دیگه روی سرعت آی پی هایی که درحال استفاده هستند تاثیر نمیزاره( اگه محدودیت پهنای باند برای هر کدوم بزاریم) و بصورت جداگانه روی چند ای پی فعال میکنیم . با تشکر از زحمات شما

**Comment by malkemit** [comment]
با سلام 
طی اخرین اپدیت رو این موضوع کار کردین اتفاقا و سرعت رو بر اساس ساعت زمانی ایران تنظیم کردیم و در ساعت هایی که کاربران کمتری از اینترنت استفاده میکند، این اسکریپت هم سرعت کمتری دارد تا مشخص نباشد


برای خواسته شما میتونید بعد از نصب اسکریپت در یک vm میزان دانلود پیشفرض را فرضا 10000 گیگ بزارید تا این اسکریپت سعی کند که تا ۱۰۰ ترا و بیشترر بسازد 
البته این مقدار دیگه با توجه به مصرف شماست و روش باید فکر کنید که چه میزان درست هست براتون. ولی در کل ترافیک های متقارن در وی ام های دیگه رو جمع کنید و اینجا وارد کنید ( ضمنا گزینه مربوط به تنظیم میزان دانلود، گزینه ۷ هست)


در مورد سرعت هم بافر رو نهایتا ۴ بزارین ولی میتونید ضریب اپلودر رو ۳۰ بزارید. فقط وی ام ایی که برای اپلود میسازید تعداد هسته خوبی داشته باشه کافیه
