### ISSUE TITLE
قطع شدن عملیات اپلود بعد از مدتی

### ISSUE THREAD

**Issue by alijoon3376** [malkemit/namizun#17]
درود 
بعد از مدتی که اسکریپت اپلود میکنه متوقف میشه و باید ریلود کنم تا دوباره شروع به اپلود کنه ممنون میشم در این خصصو راهنمایی بفرمایید

**Comment by malkemit** [comment]
سلام

ممکن هست دستور زیر را بزنید و اگر اروری رو دیدید برام بفرستید؟

journalctl -u namizun -n 100

**Comment by alijoon3376** [comment]
> 

اخرین لاگ قبل از ریلود اسکریپن
"Dec 12 01:07:23 server1.yourdomain.com systemd[1]: Stopping Namizun servi>
بعد از ریلود
"Dec 12 01:07:23 server1.yourdomain.com
 systemd[1]: namizun.service: Success>
"

**Comment by malkemit** [comment]
خب چندین خط رو بزارید 

بهتره عکس بزارین تا کامل متن ها رو ببینم و بتونم نظر بدم

**Comment by alijoon3376** [comment]
> خب چندین خط رو بزارید
> 
> بهتره عکس بزارین تا کامل متن ها رو ببینم و بتونم نظر بدم
![Uploading Screenshot_2022-12-17-21-57-07-28_61c78dc80ee02b53007c815fefe993e3.jpg…]()

**Comment by malkemit** [comment]
جناب اینجوری پشت هم قرار میگیره، ارور خوانا نیست و لطفا عکس ازش بفرستید

**Comment by alijoon3376** [comment]
> جناب اینجوری پشت هم قرار میگیره، ارور خوانا نیست و لطفا عکس ازش بفرستید

![Screenshot_2022-12-20-02-44-33-04](https://user-images.githubusercontent.com/44420340/208546544-1d4b858e-3b6b-4421-b23f-1467ae1131b8.jpg)

**Comment by malkemit** [comment]
یه باگی رو پیدا کردم و فیکس شد

لطفا بروز رسانی کنید احتمالا این مشکل برطرف شده

**Comment by alijoon3376** [comment]
توسعه دهنده عزیز
ممنون بابت پیگیری شما
بعد از اپدیت هم هنوز همونجوری هستش و هر از گاهی سرعت اپلود برابر میشه با سرعت دانلود و باید یک بار ریلود بزنم اسکریپت رو

**Comment by malkemit** [comment]
در یک زمان هایی برابر میشه و دوباره رشد میده

به هر حال شما که همیشه یک ضرب ریکوئست بزنین منطقی نیست! 

برای همین یکی دو دقیقه اف بشه عیب نداره
