### ISSUE TITLE
آپلود فایل به میزان دلخواه

### ISSUE THREAD

**Issue by Jolge100** [malkemit/namizun#18]
خسته نباشید
ممنون از اسکریپتتون فقط من یه مشکلی دارم اونم اینه که یه سزور جدا برای اپلود گذاشتم که عملا دانلودی نداره که به نسبت 1 به 10 اپلود روش انجام بشه
می خواستم ببینم چجوری می تونم مثلا عدد دانلود شده رو به دلخواه بذارم که بعد نسبت 1 به 10 اون رو اسکریپت اپلود بکنه
البته توی اینجا 
https://github.com/malkemit/namizun/issues/16
یه توضیحاتی دادید در مورد اینکه vm باز کنم اما چون ابونتو زیاد بلد نیستم متوجه نشدم دقیقا باید کدوم فایل رو ادیت کنم 
ممنون می شم راهنمایی بفرمایید

**Comment by malkemit** [comment]
با سلام

کلا برای اینکه اپلود هی انجام بشه و قطع نشه ( به عنوان مثال یکی از سرور های مجازیتون فقط فعالیت اپلود رو برعهده داره) در اون سرور بعد از اینکه نامیزون رو نصب کردید، میزان دانلود پیش فرض رو افزایش بدین

شما با زدن عدد 7 وارد منو Total Download Before Reboot میشید و اونجا فرضا عدد 1000 رو وارد کنید تا اسکریپت فرض کنه که یک ترا دانلود از قبل داشته و بیاد براش ۱۰ ترا فیک بزنه که این عمل باتوجه به ضریب هایی که اعمال کردید و طی مدت زمان نسبتا طولانی مشغول اپلود زدن خواهد بود

حالا اینکه چه ضرایبی بزارین و چه مقدار دانلود پیش فرض براش بزارید، انتخاب شماست و بنا به نیازتون تنظیم کنید

**Comment by Jolge100** [comment]
بسیار ممنونم توضیح کامل و کافی بود
