### ISSUE TITLE
اررور در مرحله 5

### ISSUE THREAD

**Issue by rainyboy7** [malkemit/namizun#19]
سلام. من وقتی مرحله ها رو پیش میرم تو مرحله 5 با این اررور برخورد میکنم. قبلا نصب کردم و اوکی بوده. الان بعد از مدتی اومدم دوباره نصب کنم این خطا رو میده. سیستم عامل رو از اول هم نصب کردم کماکان مشکل پابرجا بود

/var/www/namizun# source /var/www/namizun/venv/bin/activate && cd /var/www/namizun && pip install . && deactivate

Processing /var/www/namizun
Collecting colored~=1.4.4 (from namizun-core==1.3.3)
  Downloading https://files.pythonhosted.org/packages/f3/d6/00203998f27ab30b2417998006ad0608f236740bb129494dd7c5621861e1/colored-1.4.4.tar.gz
Collecting prettytable~=3.5.0 (from namizun-core==1.3.3)
  Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-core==1.3.3) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
No matching distribution found for prettytable~=3.5.0 (from namizun-core==1.3.3)

**Comment by malkemit** [comment]
با سلام
سرورتون اوبنتو ۲۰ نیست فکر کنم
