### ISSUE TITLE
Failed to enable unit: File namizun.service: Bad message

### ISSUE THREAD

**Issue by shahrooz1349** [malkemit/namizun#2]
hi dear developer
Thanks for this great script
I installed on Ubuntu 20 But at the end I have an error
The upload and download volumes are also the same

![Screenshot_20221124_013755_org connectbot_edit_1349158161881628](https://user-images.githubusercontent.com/87688187/203654669-bc62a222-91ef-40e7-ae31-0ff9e442a046.jpg)
![Screenshot_20221124_013403_org connectbot_edit_1349170560514959](https://user-images.githubusercontent.com/87688187/203654677-bc8bffd3-cfe5-4f7e-b3bf-4acaf7d3afed.jpg)

**Comment by malkemit** [comment]
hi
Type this command in the terminal and send me the answer

nano /etc/systemd/system/namizun.service

**Comment by shahrooz1349** [comment]
![Screenshot_20221125_204554_org connectbot_edit_1447916043430621](https://user-images.githubusercontent.com/87688187/204031889-35aa6346-9705-4c94-a55b-8a4550d62121.jpg)
Best Regards

**Comment by malkemit** [comment]
There is a problem in your writing and therefore it cannot read the system service
Use the new update
I put the service in the project and you just make a link

**Comment by shahrooz1349** [comment]
dear malkemit
Thank you for this great and useful script
I installed the new version, but the upload and download are the same. Is my problem in installing the script?
![Screenshot_20221126_001749_org connectbot_edit_1458975216040912](https://user-images.githubusercontent.com/87688187/204054315-9a54dc9e-fa2b-4530-906f-6a89e68b6e19.jpg)

@malkemit

**Comment by shahrooz1349** [comment]
![Screenshot_20221126_050607_org connectbot_edit_1475874963281042](https://user-images.githubusercontent.com/87688187/204067524-fdfac5c2-a2dd-4a72-957f-191e4160dfed.jpg)

This error occurs during installation

regards

**Comment by malkemit** [comment]
it's ok
don't worry
if you try again it seems to be ok

**Comment by shahrooz1349** [comment]
tnx dear developer
