### ISSUE TITLE
توضیح بشتر در مود پنل

### ISSUE THREAD

**Issue by alione2112** [malkemit/namizun#20]
![Capture](https://user-images.githubusercontent.com/118251449/208269531-5e8cc5ec-ece6-4524-9569-bcbf371b26bc.PNG)
سلام و تشکر بابت اسکریپ عالیتون 
من متوجه گزینه ها 6 و 7 نشدم 
و اعداد موجود در جدول که آپلود و دانلود رو نشون میدن فرقشون با گزینه 7 و 6 چی هست
من تازه نصب کردم و این اعداد رو نشون میده در جدول 
ممنون میشم راهنماییم کنید 
و اینکه آپلود در پهنای باید سرور حساب مبشه مثلا محدودیت باند  1 ترا داشته باشیم  اگه 100 گیگ دانلود کنیم اسکریپتم 10 براربرشو که میشه 1 ترا آپلود کنید  پهنای باید تموم میشه ؟
ممنون از راهنماییتون

**Comment by malkemit** [comment]
با سلام و تشکر بابت حمایتتون
اون میزان اپلود و دانلودی که در جدول بالا میبینید مقداریست که از اخرین ری استارت شدن سرورتون، داخل سرور ثبت شده (یعنی هر بار سرور ری استارت بشه اون مقدار میشه صفر)
ولی برای نامتقارن کردن، شما باید مصرف های قبل ری استارت هم در نظر بگیرید و میتوانید مقادیر مربوطه رو به وسیله گزینه ۶ و ۷ ثبت کنید.

در واقع شما با وارد کردن مقادیر پیش فرض، میزان دانلود و اپلودی که داخل پنل نوشته شده را با میزان اپلود و دانلود گراف جایی که بهتون ارائه میده یکی میکنید تا مشکلی نباشه

در مورد سوال اخرتون، این اپلود واقعی هست و رو ترافیکتون ثبت میشه.
در مورد اون بحث محدودیت ترافیک، معمولا میگن ۵۰۰ گیگ یا ۱ ترا میتونه متقارن باشه ولی بیشتر از اون باید یک به ده باشه. تو این موارد اگه مصرفتون تو یک ماه در حد همون ۵۰۰ گیگ یا ۱ ترا هست که از همون استفاده کنید و نامیزون نکنید. ولی اگر بیش از اون مصرف دارین باید نامتقارن کنید و بهشون بگین که نامتقارن هست و شما رو محدود نکنند.

اطلاعات بیشتر رو از ارائه دهنده خودتون بگیرین
