### ISSUE TITLE
بر اساس Mbps

### ISSUE THREAD

**Issue by ESI-SYS** [malkemit/namizun#21]
با سلام و دورد خدمت شما

بعضی از providerها بر اساس ترافیک حساب نمیکنن . میگن مقدار 1 به 10 بصورت Mbps حساب میشه . 
میشه کاری کرد که مثلا سرعت آپلود رو بشه تنظیم کنیم . 

یعنی هر 1مگابیت دانلود باید 10 مگابیت آپلود داشته باشیم
سپاس

**Comment by malkemit** [comment]
با سلام 
تو نسخه های فعلی این امکان نیست چون بر اساس حجم پیش میره

اما این رو تو روز های آتی اضافه میکنم بهش که این مشکل هم حل بشه

ممنون از اطلاع رسانیتون
