### ISSUE TITLE
ریست کردن حجم دانلود و اپلود شده

### ISSUE THREAD

**Issue by Jolge100** [malkemit/namizun#22]
بسیار اسکریپت عالی و کامل هستش خیلی ممنون
چطور می شه مقداری دانلود و اپلود سرور رو ریست کرد که مثلا اول هر ماه بشه ریستارتش کرد و صفر بشه و مجددا امار دست ادم باشه
ممنونم

PS: حل شد متوجه شدم با ریستارت خود سرور صفر می شه نمی دونم تو 2 بار اول چرا نشده بود
شرمنده

**Comment by malkemit** [comment]
با سلام
اینم بد ایده ایی نیست و روش فکر میکنم و اضافه میکنم به اسکریپت

**Comment by ZarinNegah** [comment]
> با سلام اینم بد ایده ایی نیست و روش فکر میکنم و اضافه میکنم به اسکریپت

سلام
واقعا اسکریپت خوب و کاربردی ساختین
ایده ای هم بابت صفر شدن ترافیک در اول هر ماه میلادی هم خوب می باشد
ولی ای کاش هر چند دقیقه ترافیک ها ذخیره میکرد و بعد از هر ریست فراخوانی میکرد
من خودم یه مشکل دارم اینه هر روز سر یه ساعت سرورها ریبوت میکنم،و این ترافیک سفر میشه کلا و هر روز باید یادم بمونه دستی تنظیم کنم،یا یادم میره روی چه میزان بود که ریست شدش

ممنون بازم
