### ISSUE TITLE
Not work for me .. 

### ISSUE THREAD

**Issue by seyyed1332** [malkemit/namizun#23]

**Comment by seyyed1332** [comment]
درود . تشکر از زحمات بسیار شما .. 

یه توضیح برای استفاده این اسکریپ به صورت ساده تر بگید . بنده نصب کردم ولی چیزی انجام نشد .. و ترافیک هم رصد نمیشد و 0 بود

**Comment by M4hbod** [comment]
توی کانال تلگرامشون کامل توضیح دادن
https://t.me/ExplainLikeIam5
