### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by payamix** [malkemit/namizun#25]
سلام، موقع نصب این ارور رو میده:
ERROR: Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-core) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
ERROR: No matching distribution found for prettytable~=3.5.0

**Comment by malkemit** [comment]
سلام رو اوبنتو ۲۰ تست کنید
