### ISSUE TITLE
نبودن منو

### ISSUE THREAD

**Issue by Real-kia** [malkemit/namizun#29]
![image](https://user-images.githubusercontent.com/65906956/209635963-89d7b762-6e26-4cfe-909e-8f5340a2727f.png)

**Comment by malkemit** [comment]
سلام اندازه صفحه ترمینال رو بزرگتر کنید و بعد یه بار دیگه بزنین ببینین چطوریاست

**Comment by Real-kia** [comment]
![image](https://user-images.githubusercontent.com/65906956/209697895-056f7acd-b033-421b-a4fe-b33a8bfb3331.png)

**Comment by Real-kia** [comment]
اگه یک دور سرور را ریبوت کنم درست میشه

**Comment by malkemit** [comment]
بسیار عالی

اسکریپت رو اپدیت کنید شاید این هم کمک کنه
