### ISSUE TITLE
مشکل دانلود پیش نیاز در سرور

### ISSUE THREAD

**Issue by Zo0oX** [malkemit/namizun#30]
سلام

متاسفانه خط اول این ارور رو میده، راه حلش چی هست ؟

`Ign:1 http://ir.archive.ubuntu.com/ubuntu focal-updates/main amd64 libatomic1 am                      d64 10.3.0-1ubuntu1~20.04
Err:2 http://ir.archive.ubuntu.com/ubuntu focal/universe amd64 libhiredis0.14 amd64 0.14.0-6
  Temporary failure resolving 'ir.archive.ubuntu.com'
Err:3 http://ir.archive.ubuntu.com/ubuntu focal/universe amd64 libjemalloc2 amd64 5.2.1-1ubuntu1
  Temporary failure resolving 'ir.archive.ubuntu.com'
0% [Connecting to ir.archive.ubuntu.com]
`

**Comment by malkemit** [comment]
سلام از تغییر dns که در کانال گذاشتم استفاده کنید 
https://t.me/ExplainLikeIam5/12

**Comment by Zo0oX** [comment]
ممنونم اون مرحله رد شد

الان اینجا این ارور رو میده


`(venv) root@ir5:/var/www/namizun# source /var/www/namizun/venv/bin/activate && cd /var/www/namizun && pip install wheel && pip install . && deactivate
Requirement already satisfied: wheel in ./venv/lib/python3.8/site-packages (0.38.4)
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by malkemit** [comment]
cd /var/www/namizun && source /var/www/namizun/venv/bin/activate && pip install wheel && pip install namizun_core/ namizun_menu/ && deactivate


دستوراپدیت شده

**Comment by Zo0oX** [comment]
من 0 رو زدم خارج شدم

الان میخوام باز کنم این مشکل رو دارم

`namizun
bash: /usr/local/bin/namizun: Permission denied
`
