### ISSUE TITLE
Permission denied after update to 1.3.8

### ISSUE THREAD

**Issue by lord4170** [malkemit/namizun#31]
-bash: /usr/local/bin/namizun: Permission denied

سلام و خدا قوت دوست عزيز  ، بعد از اپدیت به ورژن جديد نمشه نامیزون رو اجرا کرد . ارور دسترسی میده

**Comment by malkemit** [comment]
دستور اپدیت رو مجدد بزنین 

به نظرم

chmod +x /usr/local/bin/namizun

این بخش رو نزدین

میتونین این دستور رو به تنهایی بزنین ولی به نظرم بهتره یکبار دستور اپدیت رو بزنین

**Comment by lord4170** [comment]
درود به استاد بزرگ . حل شد
