### ISSUE TITLE
تشخیص نامیزون

### ISSUE THREAD

**Issue by Real-kia** [malkemit/namizun#34]
سلام من امروز به یکی از سایت های فروش وی پی اس زنگ زدم و درباره ی نسبت اپلود به دانلود پرسیدم
گفتند که یک به هشت هست
ولی اگر اون اسکریپت را ران کنی توسط دیتا سنتر شناسایی میشود و ترافیک اپلود حساب نمیشود

**Comment by malkemit** [comment]
سلام
اگر دیتاسنتر تشخیص بده بله قبول نمیشه! اما اگر تشخیص بده

قبلا در هر تایم سرعت تقریبا ثابت بود و مثلا ۳ صبح با سرعت بالایی ارسال میکرد و اینجوری تشخیص میدادن
الان رنج ای پی ها و سرعت ارسال و پورت ها منطقی تر شده

یک مورد فعلا گزارش شده و اونم سرعت در لحظه هست که به زودی برطرف میکنمش

با این وجود اگر رفتار خاصی از اسکریپت دیدین که باعث این اتفاق میشه، ممنون میشم بهم بگین تا اون هم برطرف کنم

**Comment by Real-kia** [comment]
اگر پهنای باند مصرفی شما (در لحظه) 1 به 10 باشد، بله. به‌عبارت دیگر، اگر از VPS برای تولید محتوا استفاده شود.
زمانی که به‌صورت Real Time شبکه سرور مانیتور می‌شود. اگر شما سرویس‌دهنده باشید، به‌راحتی از پهنای باند نامحدود و رایگان بهره‌مند می‌شوید. در صورت استفاده از سرویس برای تانلینگ، پهنای باند نامحدود ارائه نخواهد شد.

من منظورشون را دقیق متوجه نشدم.
منظورشون این هست که همون لحظه ای که دانلود انجام میشه اپلود ۱۰ برابر باشه؟
همچین قابلیتی نامیزون داره؟

**Comment by malkemit** [comment]
اولین مشکلی که هست اینه که الگو ارسال دیتا تکراری باشه
مثلا وقتی شما تو روش های دیگه از کرون جاب استفاده میکنید یا اندازه فایل ارسالی شما مثلا همیشه ۵۰۰ مگ هست یا به یه ای پی خاص (دامین خاص) هی ارسال میکنید، الگو تکراریه

در نامیزون اینا برطرف شده، یعنی مقدار فایل، ای پی مقصد ، زمانبندی ها و تعداد ارسال با توجه به ساعت رسمی ایران متفاوت میشه و همچنین نامحدود و پشت سر هم اپلود نمیشه و  به میزان مصرف شما بستگی داره. رو این حساب فعلا تا حدی میتونه مخفی باشه

اما وقتی نامیزون شروع به اپلود میکنه برای چند دقیقه حدودا سرعتش ثابته( به هر حالا مقداری حجم به تعدادی ای پی باید ارسال بشه) و مثل اینکه سر این موضوع مشکل ایجاد شده.

رو همین حساب سعی میکنم بخشی بهش اضافه کنم که در لحظه با توجه به میزان سرعت، سرعت ارسال فیک رو تنظیم بکنه

تو چند روز اینده این اپدیت رو اضافه میکنم
