### ISSUE TITLE
خطا بعد از اجرا دستور شماره 5

### ISSUE THREAD

**Issue by bahr4m** [malkemit/namizun#35]
سلام. خسته نباشید. ممنون بابت زحماتتتون.
بعد از اجرا دستور شماره 5 روی سرور ایران این خطا رو دریافت میکنم و نمیدونم از چی میتونه باشه:
` Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-menu==1.0.0) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
No matching distribution found for prettytable~=3.5.0 (from namizun-menu==1.0.0)`

ممنون میشم راهنمایی کنین

**Comment by malkemit** [comment]
سلام باید رو پایتون ۳.۸ اجرا بشه 

روی اوبونتو۲۰ تست کنید

**Comment by samankhademi1** [comment]
سلام با اجازه استاد
واسه رد کردن این ارور دستور رو خودتون دستی کبی کنید و از کبی سایت استفاده نکنید
