### ISSUE TITLE
کانفیگ کردن + چندتا ویژگی

### ISSUE THREAD

**Issue by karimi12** [malkemit/namizun#36]
سلام جای یک کانفیگ فایل خالی هست 
علاوه بر این دیتا سنتر ها اگر بهت شک کنن وصل می شن به سرور و فرایند ها چک می کنن
دوتا چیز باید اضافه بشه یکی امکان نصب اسکریپت با یک اسم دلخواه  و دیگری امکان دانلود از یک سری فایل مشخص مثلا روی چندتا سرور این اکریپت اجرا بشه ( به عنوان کلاینت) اونا بیان از سرور اصلی دانلود کنن 
فقط  نرم افزار باید فایل با اسامی و حجم های مختلفی بساز
جهت بر قراری اتصال مشخص و جهت برقراری اتصال آپلود کاملا مشخص ویژگی بعدی که باید اضافه بشه باید پورت ثابتی باز بشه برای اپلود مثلا همیشه پورت 80 استفاده بشه دقیقه مشابه وب سرور ها در اپلود از سمت سرور شماره پورت رندم 

اینا یک سری پیشنهاد من بود که باید  به سیستم نرم افزار اضافه بشه تا تشخیصش سختر بشه

**Comment by malkemit** [comment]
سلام 
در مورد اینکه اسم کاستوم باشه، ایده بدی نیست. یکم دردسر داره  اما سعی میکنم کاری کنم که تو یک فایل اینوارمنت همه اینا رو اضافه کنین

در مورد موضوع دوم ایده خوبیه. فقط من به جای اینکه اینجا فایل بسازم و سرور دیگه ایی دانلود کنه، یک اسکریپت میسازم رو سرور دریافت کننده بزارین و نامیزون اپلود بکنه. اینجوری سرعت رو میشه در زمان های متفاوت راحت تر مدیریت کرد

**Comment by karimi12** [comment]
برای مثال بتونیم زمانبدی بدیم برای اجرا مثلا در این ساعات کار کن 
در سی روز این مقدار اپلود کن 
از پورت n  استفاده کن
