### ISSUE TITLE
I've got UnicodeEncodeError  

### ISSUE THREAD

**Issue by proshutdev** [malkemit/namizun#37]
File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/namizun/namizun_menu/main_menu.py", line 19, in menu
    print(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03a3' in position 251: ordinal not in range(256)

**Comment by malkemit** [comment]
سلام

اینکد سرور شما به جای utf8 فکر کنم latin هست و تو بعضی از دستور های print مشکل میخوره

متاسفانه چون این سبک سرور ندارم، از اینکه چه تغییری توی کد بدم، ایده ایی ندارم
شما یه سرچ بزنین. حتما راه حل هایی هست که اینکد دیفالت سرورتون رو uft8 بکنید

**Comment by proshutdev** [comment]
Thanks man. I've changed locale to en_US.UTF-8 and It works.I'm waiting for result of your script and I hope it works
