### ISSUE TITLE
خطا Permission denied

### ISSUE THREAD

**Issue by Jafarahmadii** [malkemit/namizun#42]
با سلام. من تمامی مراحل رو انجام دادم. حتی DNS رو هم تغییر دادم. ولی در پایان کار که میخوام دستور namizun رو اجرا کنم، این خطا رو میده:

root@ubuntu20:/var/www/namizun# -bash: /usr/local/bin/namizun: Permission denied

**Comment by malkemit** [comment]
دستور اپدیت رو بزنین 

cd /var/www/namizun && git reset --hard HEAD && git pull origin master && source /var/www/namizun/venv/bin/activate && pip install namizun_core/ namizun_menu/ && deactivate && systemctl daemon-reload && chmod +x /usr/local/bin/namizun
