### ISSUE TITLE
نصب نسخه قدیم

### ISSUE THREAD

**Issue by Jolge100** [malkemit/namizun#43]
می خواستم ببینم نسخه قدیم رو چطور می تونم نصب کنم 
این نسخه جدید تایم اوت می اندازه روی سرورم ولی با اون قدیمیه مشکلی نداشتم
ممنونم

**Comment by malkemit** [comment]
سلام 

متوجه مشکل تایم اوت نشدم

ممکن هست واضح تر بیان کنین؟

**Comment by Jolge100** [comment]
> سلام
> 
> متوجه مشکل تایم اوت نشدم
> 
> ممکن هست واضح تر بیان کنین؟

مشکلی که دارم اینه که این نسخه جدید یهو سرعتش زیاد می شه و می رسه با ماکزیمیم سرعت سرورم و برای همین سرورم برای چند ثانیه تایم اوت می ده مثل هنگ شدن
دلیلیش رو نمی دونم چرا اینجوری می شه 
یک سرور هم نیست همه اینجوری می شه
اگه بتونین مثلا یه ماکزیمم سرعت اپلود براش تعیین کنین
یعنی حتی اگه 30 ترید هم گذاشتیم سرعت از یه حدی بالاتر نره مشکل ادم هایی مثل من احتمالا حل می شه
اون نسخه قدیمی رو هم نفرمودید چطور می تونم نصب کنم

**Comment by Jolge100** [comment]
و یه مساله دیگه اگه امکانش هست لیمیت اپلود شبانه رو اجازه برداشتن بدین چون خودم مثلا به شخصه حجم زیادی از جبران اپلودم رو شب ها که سرورم سبک هستش انجام می دم
ممنونم

**Comment by malkemit** [comment]
تنظیماتی که برای اسکریپت ست کردین رو بهم بگین؟

اسکریپت نمیتونه یهویی نمیتونه کل نتورک سرور رو پر بکنه 
حس میکنم شما تنظیمات رو همینجوری عدد اخر گذاشتین و این مشکل احتمالا براتون پیش اومده و خب منطقا باید ضرایبی که گذاشتین رو کمتر کنین
اگر ضرایب رو درست بزارین، اسکریپت سرعتش از یه حد بیشتر نمیشه

برای چی باید ضریب تعداد اپلودر رو ۳۰ بزارین و بعد بخواین سرعت اسکریپت محدود بشه؟ خب تعداد اپلودر بزارین رو ۱۰:/

این موضوع تو همه نسخه ها بوده و نسخه خاصی نیست که این کار رو نکنه


ضمنا اون خواسته اینکه سرعت در شب کمتر میشه رو بردارم، یک اشتباه محضه. چون گرافتون غیر منطقی میشه و سرورتون رو میبندن
