### ISSUE TITLE
ارورر هنگام نصب 

### ISSUE THREAD

**Issue by rezakhosh78** [malkemit/namizun#46]
با سلام و وقت بخیر هنگام نصب اسکریپت cd /var/www/namizun && source /var/www/namizun/venv/bin/activate && pip install wheel && pip install namizun_core/ namizun_menu/ && deactivate ارورهای زیر رو دریافت میکنم:

HEAD is now at 02cf17d namizun v1.3.8.2 - readme.md updated
From https://github.com/malkemit/namizun
 * branch            master     -> FETCH_HEAD
Already up to date.
Processing ./namizun_core
Processing ./namizun_menu
Collecting psutil==5.9.4 (from namizun-core==1.3.8)
  Using cached https://files.pythonhosted.org/packages/3d/7d/d05864a69e452f003c0d77e728e155a89a2a26b09e64860ddd70ad64fb26/psutil-5.9.4.tar.gz
Collecting pytz==2022.6 (from namizun-core==1.3.8)
  Using cached https://files.pythonhosted.org/packages/85/ac/92f998fc52a70afd7f6b788142632afb27cd60c8c782d1452b7466603332/pytz-2022.6-py2.py3-none-any.whl
Collecting redis==4.3.5 (from namizun-core==1.3.8)
  Using cached https://files.pythonhosted.org/packages/76/ad/dd7b6423295394b95e03d961d454e3046b569715dcc2dd4a030bb43a7cff/redis-4.3.5-py3-none-any.whl
Collecting colored~=1.4.4 (from namizun-menu==1.0.0)
  Using cached https://files.pythonhosted.org/packages/f3/d6/00203998f27ab30b2417998006ad0608f236740bb129494dd7c5621861e1/colored-1.4.4.tar.gz
Collecting prettytable~=3.5.0 (from namizun-menu==1.0.0)
  Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-menu==1.0.0) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
No matching distribution found for prettytable~=3.5.0 (from namizun-menu==1.0.0)

**Comment by hdNasehi** [comment]
> با سلام و وقت بخیر هنگام نصب اسکریپت cd /var/www/namizun && source /var/www/namizun/venv/bin/activate && pip install wheel && pip install namizun_core/ namizun_menu/ && deactivate ارورهای زیر رو دریافت میکنم:
> 
> HEAD is now at [02cf17d](https://github.com/malkemit/namizun/commit/02cf17d91cabda163f7a0a605b7a473f4ce92529) namizun v1.3.8.2 - readme.md updated From https://github.com/malkemit/namizun
> 
> * branch            master     -> FETCH_HEAD
>   Already up to date.
>   Processing ./namizun_core
>   Processing ./namizun_menu
>   Collecting psutil==5.9.4 (from namizun-core==1.3.8)
>   Using cached https://files.pythonhosted.org/packages/3d/7d/d05864a69e452f003c0d77e728e155a89a2a26b09e64860ddd70ad64fb26/psutil-5.9.4.tar.gz
>   Collecting pytz==2022.6 (from namizun-core==1.3.8)
>   Using cached https://files.pythonhosted.org/packages/85/ac/92f998fc52a70afd7f6b788142632afb27cd60c8c782d1452b7466603332/pytz-2022.6-py2.py3-none-any.whl
>   Collecting redis==4.3.5 (from namizun-core==1.3.8)
>   Using cached https://files.pythonhosted.org/packages/76/ad/dd7b6423295394b95e03d961d454e3046b569715dcc2dd4a030bb43a7cff/redis-4.3.5-py3-none-any.whl
>   Collecting colored~=1.4.4 (from namizun-menu==1.0.0)
>   Using cached https://files.pythonhosted.org/packages/f3/d6/00203998f27ab30b2417998006ad0608f236740bb129494dd7c5621861e1/colored-1.4.4.tar.gz
>   Collecting prettytable~=3.5.0 (from namizun-menu==1.0.0)
>   Could not find a version that satisfies the requirement prettytable~=3.5.0 (from namizun-menu==1.0.0) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
>   No matching distribution found for prettytable~=3.5.0 (from namizun-menu==1.0.0)

I Have same error too. I want install prettytable but id dos not extsts in repository

**Comment by malkemit** [comment]
hi

This problem is due to the Python version
Python must be 3.8
