### ISSUE TITLE
An error occurred while installing the prerequisites

### ISSUE THREAD

**Issue by Kasike7** [malkemit/namizun#48]
سلام . 
من بعد از اجرای کد این خطا رو میگیرم :
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1731  100  1731    0     0   4716      0 --:--:-- --:--:-- --:--:--  4716
Install prerequisites (step 1)
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:5 https://download.docker.com/sudo apt-get InRelease
Err:6 https://download.docker.com/sudo apt-get Release
  404  Not Found [IP: 52.85.49.70 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/sudo apt-get Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
An error occurred while installing the prerequisites

ممنون میشم راهنمایی کنید

**Comment by malkemit** [comment]
سلام رو سرور شما داکر هست؟ فکر کنم مشکل nameserver دارین

نیم سرور های فایل resolv.conf رو تغییر بدین

**Comment by Kasike7** [comment]
بله داکر هست . ببخشید من اطلاعاتم خیلی کمه در این زمینه . 
باید این نیم سرورها رو به چی تغییر بدم؟

**Comment by malkemit** [comment]
چون داکر ایران رو تحریم کرده، برای همین باید نیم سرور های dns سرورتون رو تغییر بدین
میتونین از نیم سرور های شکن استفاده کنید
https://shecan.ir/

nano /etc/resolv.conf
با این دستور فایل dns ریسالو رو باز کنین و 
nameserver 178.22.122.100
nameserver 185.51.200.2
و این دو جمله قرار بدین و در نهاید ctrl +o و ctrl + x
