### ISSUE TITLE
نحوه نصب بر روی centos 7

### ISSUE THREAD

**Issue by bestkilleriranlod** [malkemit/namizun#49]
سلام اسکریپت رو که میخوام روی centos 7 اجرا کنم ارور میده و انجام نمیشه
لطفا راهنمایی کنید برای centos چطوری باید نصب انجام بشه
ممنون از زحماتتون

**Comment by malkemit** [comment]
سلام باید پایتون ۳.۸ دیفالت باشه که نیست و به راحتی نصب نمیشه و پیشنهاد میشه اوبونتو ۲۰ استفاده کنید

**Comment by bestkilleriranlod** [comment]
ممنون میشم اگه راهی برای نصب روی centos هم ایجاد کنید

**Comment by malkemit** [comment]
بهترین راهکار داکر هست ولی مشکلی که هست وقتی پروژه داکرایز باشه نمیتونه مقدار حجمی که شما عبور میدین رو بفهمه 

ولی تو برنامم هست یه ابزار برای تونل کردن بسازم که نامیزون باهاش در ارتباط باشه و اون وقت دیگه مشکلی از بابت داکرایز کردن نباشه

**Comment by bestkilleriranlod** [comment]
ممنون از زحماتتون
