### ISSUE TITLE
ارور warning 

### ISSUE THREAD

**Issue by Maleficent-v** [malkemit/namizun#50]
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/wheel/
ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
ERROR: No matching distribution found for wheel
Dependencies doesn't installed correctly

سلام با این ارور که روی ubuntu 22 میگیرم باید چیکار کنم ؟

**Comment by bestkilleriranlod** [comment]
منم همین مشکل دارم روی بعضی سرور ها

**Comment by malkemit** [comment]
سرور هایی که تهیه کردین مشکل اینترنت دارند

در واقع محدودیت هایی برای دانلود پکیج ها از سایت هاشون دارند مثل pypi.org

احتمالا با تغییر nameserver حل بشه ولی چک کنید چه نیم سروری به کار میاد

**Comment by bestkilleriranlod** [comment]
چه نیم سروری پیشنهاد میدید برای حل این مشکل

**Comment by Vahid-Spacer** [comment]
Salam mnm in moshkel ro daram chikar konm?

**Comment by lord4170** [comment]
متاسفانه با کلی نیم سرور تست ردم از جمله شکن ولی باز نصب نمیشه . راه حل دیگه ای براس نصب این پکیج نیست ؟

**Comment by bestkilleriranlod** [comment]
یک راه حل براش پیدا کردم فقط شاید یکم کثیف باشه
از روی یک سروریکه namizun نصب کردید برید به مسیر نصب /var/www/ و پوشه namizun رو زیپ کنید و دانلود کنید
بعد روی هر سروریکه میخواید توی همین مسیر اپلودش کنید و بعد دستور آپدیت اسکریپت رو بزنید تا نصب و فعال بشه
تمام

**Comment by mahmood2395** [comment]
انگار فایل های پروژه از تو pypi.org حذف شدن
من نتونستم پیداشون کنم
حتی با vpn رو سیستم خونه هم دانلود نشد
@malkemit عزیز یه بررسی میکنید لطفا؟

**Comment by malkemit** [comment]
سلام پکیج ها که از pypi.org حذف نشدن که،اونا سرجاش هستند

**Comment by mahmood2395** [comment]
آخه من تو پروژه های سایت سرچ زدم نبود و اسکریپت نصب رو هم که اجرا میکنم اخرش این ارور رو میگیرم
ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
ERROR: No matching distribution found for wheel
dns ها هم شکن هستن
رو اوبونتو 22 خونه هم که با vpn هست همین ارور رو گرفتم

**Comment by malkemit** [comment]
تو سایت که پروژه ایی به اسم نامیزون ثبت نکردم که
از تعدادی از پکیج هاش استفاده میشه که اونا همش توی pypi.org هست

چیزی که مشخصه این ها اختلال هایی هست که رو سرور هاشون گذاشتن که شما به مشکل بخورین
یه فایل زیپ توی تلگرام میزارم بلکه با اون نصب بکنید!

**Comment by mahmood2395** [comment]
بسیار عالی
ممنون میشم

**Comment by sepehrsohrabii** [comment]
سلام دوستان من هنوز موفق نشدم به نصب همچنان این ارور رو روی سرور های آسیاتک میگیرم.
فایل زیپی هم توی کانال پیدا نکردم.

**Comment by sepehrsohrabii** [comment]
با تغییر هاست pip توی فایل setup.sh مشکل رو حل کردم و پول ریکوست زدم واستون.

**Comment by sepehrsohrabii** [comment]
از این لینک استفاده کردم.
https://blog.csdn.net/han_hhh/article/details/105693675

**Comment by malkemit** [comment]
https://t.me/ExplainLikeIam5/28

نصب دستی رو گذاشتم که اگر راهی نبود نصب بشه

**Comment by malkemit** [comment]
@sepehrsohrabii 
مرسی ازتون ولی یه چیزی که هست فکر میکنم این mirror ها رو میزنن

امیدوارم دیر تر بزنن

**Comment by lord4170** [comment]
دوست عزيز بعد از نصب دستی  برا اجرا خطای زیر رو میده :

root@Iran:~# namizun
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/var/www/namizun/venv/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.executable = '/var/www/namizun/venv/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fe2dccb8740 (most recent call first):
<no Python frame>

**Comment by malkemit** [comment]
@lord4170 
سلام 
sudo apt install python3-pip python3-venv redis git -y

پیش نیاز ها نصب شده؟

**Comment by lord4170** [comment]
بله نصب شده

root@Iran:~# sudo apt install python3-pip python3-venv redis git -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.0.2+dfsg-1).
redis is already the newest version (5:6.0.16-1ubuntu1).
git is already the newest version (1:2.34.1-1ubuntu1.6).
python3-venv is already the newest version (3.10.6-1~22.04).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.

**Comment by malkemit** [comment]
ایده  خاصی ندارم راستش، چون باهاش رو به رو نشدم. تو سرچ هم چیز به درد بخوری پیدا نکردم

به نظرم میاد os سرور کاستوم شده و نیاز هست یه تغییراتی روبهش بدی.

**Comment by sepehrsohrabii** [comment]
اگر نصب دستی کار نکرد از این اسکریپت استفاده کنین توش میرور استفاده کردم برای نصب ریوکایرمنت ها. تو سرور من جواب داد اگر هم نداد خودتون لینک میرورش رو توی setup.sh تغییر بدین.
sudo curl https://raw.githubusercontent.com/sepehrsohrabii/namizun/master/else/setup.sh | sudo bash

**Comment by Jolge100** [comment]
> اگر نصب دستی کار نکرد از این اسکریپت استفاده کنین توش میرور استفاده کردم برای نصب ریوکایرمنت ها. تو سرور من جواب داد اگر هم نداد خودتون لینک میرورش رو توی setup.sh تغییر بدین. sudo curl https://raw.githubusercontent.com/sepehrsohrabii/namizun/master/else/setup.sh | sudo bash

این برام جواب داد
ممنون داداش

**Comment by BenyaminMoadab** [comment]
واسه من این ارور رو میده

ln: failed to create symbolic link '/etc/systemd/system/namizun.service': File exists
Creating service was failed


کسیی راهکاری داره؟؟

**Comment by AkramiPro** [comment]
```
sudo setenforce 0
sudo systemctl stop namizun.service
sudo systemctl disable namizun.service
sudo rm -rf /usr/local/bin/namizun
sudo rm -rf /var/www/namizun
sudo rm -rf /etc/systemd/system/namizun.service
sudo yum install epel-release -y
sudo yum install redis git python3 python3-pip python3-devel -y
sudo systemctl restart redis.service
sudo systemctl enable redis.service
mkdir -p /var/www/namizun && cd /var/www/namizun
git init
git remote add origin https://github.com/malkemit/namizun.git
git pull origin master
python3 -m venv /var/www/namizun/venv
sed -i 's/prettytable~=3\.5\.0/prettytable~=2.5.0/' /var/www/namizun/namizun_menu/setup.py
cd /var/www/namizun
source /var/www/namizun/venv/bin/activate
pip install --upgrade pip
pip install wheel
pip install namizun_core/ namizun_menu/
deactivate
ln -s /var/www/namizun/else/namizun.service /etc/systemd/system/
sudo chmod +x /etc/systemd/system/namizun.service
sudo systemctl daemon-reload
sudo systemctl enable namizun.service
sudo systemctl restart namizun.service
ln -s /var/www/namizun/else/namizun /usr/local/bin/
sudo chmod +x /usr/local/bin/namizun
namizun
```
