### ISSUE TITLE
سرور ایرانی

### ISSUE THREAD

**Issue by fulcrum22** [malkemit/namizun#53]
از کجا سرور ایرانی بخریم که مشکلی پیش نیاد ؟ اکثر سایتا که احراز هوئیت میخوان و همین مسئله خودش خطرناکه سایت خارجی هم اکثرا 50 دلار میگیرن برای یه سرور شت 4 دلاری
راهی پیشنهاد میدین؟

**Comment by malkemit** [comment]
تنها راهی که هست اینه که سرورتون رو برای افراد زیاد به اشتراک نزارین

کلا خرید سرور ایرانی = دردسر
