### ISSUE TITLE
Torrent

### ISSUE THREAD

**Issue by ea1234567** [malkemit/namizun#56]
سلام و خسته نباشید
میدونم سوالم کاملا بی ربط هست
من به پیشنهاد آقای امین انوری اسکریپت جلوگیری از تورنت رو روی سرورم نصب کردم،الان چجوری باید پاکش کنم با چه دستوری؟
به خود آقای انوری پیام دادم،فرمودن که باید از شما بپرسم و مثل اینکه سازنده اسکریپت شما هستید
با تشکر

**Comment by ea1234567** [comment]
؟؟؟

**Comment by malkemit** [comment]
سلام

در مورد این موضوع اطلاعی ندارم
