### ISSUE TITLE
Bug:network io traffic count logic is error.

### ISSUE THREAD

**Issue by shadu120** [malkemit/namizun#59]
My server has:
- eth0
- loopback
- wg0
- tun0

`tun0` and `wg0` is runing one `eth0`.

Current logic:
```python
def get_network_io():
    io = net_io_counters()
    return io.bytes_sent + database.get_parameter('upload_amount_synchronizer') \
        , io.bytes_recv + database.get_parameter('download_amount_synchronizer')
```

This script count all the traffic of Ethernets, but not a specific one, such as "eth0".
Namizun should allow user to customize which physic networks shoud be counted in list.

An option logic
Current logic:
```python
def get_network_io():
    io = net_io_counters(pernic=True)['eth0']
    return io.bytes_sent + database.get_parameter('upload_amount_synchronizer') \
        , io.bytes_recv + database.get_parameter('download_amount_synchronizer')
```

**Comment by malkemit** [comment]
Hello
I will rewrite the script again and create a new scenario that includes Docker

For this issue, I will do something that will not be a problem
