### ISSUE TITLE
بروز نبودن توضیحات پنل در گیت هاب

### ISSUE THREAD

**Issue by admiraltidebringer** [malkemit/namizun#8]
سلام و تشکر
دوست عزیز یه ایرادی هست که گزینه های پنل، با گزینه های داخل readme.md گیت هاب یکی نیستند. پیشنهاد می کنم توضیحات گیت هاب رو به روز کنید. با تشکر

**Comment by malkemit** [comment]
با سلام اپدیت شد

مرسی از اطلاع رسانیتون
